language: objective-c
osx_image: xcode7.3
xcode_project: WMPageController-Swift.xcodeproj
xcode_scheme: WMPageController-Swift
xcode_sdk: iphonesimulator9.3
env:
  global: 
    - FRAMEWORK_NAME=WMPageController-Swift
before_install:
  - brew update
  - brew install carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  # - carthage bootstrap  
before_deploy:
  - carthage build --no-skip-current
  - carthage archive WMPageController-Swift

