language: objective-c
osx_image: xcode7.3
xcode_project: WMPageController-Swift.xcodeproj
xcode_scheme: WMPageControllerSwiftFramework
xcode_sdk: iphonesimulator9.3
env:
  global: 
    - FRAMEWORK_NAME=WMPageControllerSwiftFramework
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  # - carthage bootstrap  
before_deploy:
  - carthage build --no-skip-current
  - carthage archive WMPageControllerSwift
deploy:
  provider: releases
  api_key: deploy:
  provider: releases
  api_key: 0034796ede57eea3ab106b32da9e967ee02efeeb 
  file: WMPageControllerSwift.framework.zip 
  skip_cleanup: true
  on:
    tags: true
